
class QByteArray:
	def __init__(self, data: bytes) -> None: ...
	def data(self) -> bytes: ...

def qCompress(bstr: QByteArray, level: int) -> QByteArray: ...
def qUncompress(bstr: QByteArray) -> QByteArray: ...

